version: '3' 
services:
  tests:
    build: ./todo-app/tests
    image: todotests
    restart: always
    environment:
      FRONT_HOST: front-end
    depends_on:
      - front-end

  back-end:
    build: ./todo-app/back-end
    image: todobackend
    restart: always
    ports:
      - 3001:3001

  front-end:
    build: ./todo-app/front-end
    image: todofrontend
    restart: always
    ports:
      - 3000:3000
    environment:
      REACT_APP_API_HOST: back-end
    depends_on:
      - back-end